swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains availables API endpoints for users' transactions in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
  /user/account/:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account
      description: API for Account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User Account retrieved successully
          schema:
            $ref: "#/definitions/AccountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/account/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction
      description: API for Account Transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User Account Transaction edited successully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          balance:
            type: string
          transactions:
            type: object
  TransactionResponse:
    type: object
    properties:
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
