swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains availables API endpoints for users' transactions in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
  /user/account{id}:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account
      description: API for Account
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Account retrieved successully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account{id}/transaction{id}:





























  /user/profile/account/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction
      description: API for Account Transactions
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        "200":
          description: User Account Transaction loaded successully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction Category and Note API
      description: API for updating a user transaction's Category and Notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction category and notes
          required: true
          schema:
            $ref: "#/definitions/TransactionResponse"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error



















securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:

  Account:
    type: object
    properties:
      id:
        type: string
      balance:
        type: string
      transactions:
        type: object

  CustomTransaction:
    type: object
    properties:
      id:
        type: string
      category:
        type: string
      notes:
        type: string

  Transaction:
    type: object
    properties:
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
