swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains availables API endpoints for users' transactions in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
  /accounts:
    get:
      tags:
        - Account Module
      summary: Every Accounts API
      description: API for every Accounts
      operationId: getEveryAccounts
      produces:
        - application/json
      responses:
        "200":
          description: Every Accounts retrieved successfully
          schema:
            $ref: "#/definitions/EveryAccounts"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Accounts not found"
      security:
      - api_key: []
# -----------------------------------------------------------------
  /accounts/account{id}:
    get:
      tags:
        - Account Module
      summary: Single Account API
      description: API for a single Account
      operationId: getAccount
      parameters:
        - in: path
          name: id
          description: ID of Account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Account retrieved successfully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Account not found"
      security:
      - api_key: []
# -----------------------------------------------------------------
  /transactions/{accountId}/{dateDebut}/{dateFin}:
    get:
      tags:
        - Transaction Module
      summary: Transactions Filtered Over Time API
      description: API for fetching every Transactions of a user Account over a specified amount of time
      operationId: getAccountTransactions
      parameters:
        - in: path
          name: accountId
          description: ID of Selected User Account
          required: true
          type: string
        - in: path
          name: dateDebut
          description: Starting Day for Selecting Transactions
          required: true
          type: string
        - in: path
          name: dateFin
          description: Ending Day for Selecting Transactions
          required: true
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Transactions loaded successfully
          schema:
            $ref: "#/definitions/AccountTransactions"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Transactions not found"
      security:
      - api_key: []
# -----------------------------------------------------------------
  /transactions/{accountId}/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for Details of a Transaction
      operationId: listTransactionInfos
      parameters:
        - in: path
          name: accountId
          description: ID of Selected User Account
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of Selected Transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions loaded successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Transaction not found"
      security:
      - api_key: []
# -----------------------------------------------------------------
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction Update API
      description: API for updating a Transaction's Category & Notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: ID of Selected User Account
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of Selected Transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction category and notes attributes
          required: true
          schema:
            $ref: "#/definitions/CustomizeTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
# -----------------------------------------------------------------
# -----------------------------------------------------------------
# -----------------------------------------------------------------
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
# -----------------------------------------------------------------
definitions:
  EveryAccounts:
    type: object
    properties:
      accounts:
        type: array
        items:
          type: object          
# -----------------------------------------------------------------
  Account:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      balance:
        type: string
      description:
        type: string
      transactions:
        type: array
        items:
          type: object
# -----------------------------------------------------------------
  AccountTransactions:
    type: object
    properties:
      accountId:
        type: string
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            date:
              type: string
            description:
              type: string
            amount:
              type: string
            balance:
              type: string
# -----------------------------------------------------------------
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
# -----------------------------------------------------------------
  CustomizeTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
# -----------------------------------------------------------------