swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains availables API endpoints for users' transactions in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
  /user/account{id}:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account API
      description: API for Account
      parameters:
        - in: path
          name: id
          description: ID of Account
          required: true
          type: string
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Account retrieved successfully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
# -----------------------------------------------------------------
  /user/account{id}/transaction{id}:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Transaction details API
      description: API for fetching a Transaction
      parameters:
        - in: path
          name: id
          description: ID of Transaction
          required: true
          type: string
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction loaded successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
# -----------------------------------------------------------------
    patch:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Transaction details API
      description: API for updating a Transaction
      parameters:
        - in: path
          name: id
          description: ID of Transaction
          required: true
          type: string
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction category and notes attributes
          required: true
          schema:
            $ref: "#/definitions/CustomTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
# -----------------------------------------------------------------
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Account:
    type: object
    properties:
      id:
        type: string
      balance:
        type: string
      transactions:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: string
  CustomTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
